import = ["/home/grfreire/.config/alacritty/themes/tokyo-night.toml"]

[font]
size = 24

[font.normal]
family = "Cascadia Code"

[scrolling]
history = 100000

[window]
opacity = 0.8

[window.dimensions]
columns = 120
lines = 35
